/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "AsyncStateMachine": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
    "CheckProcessingStatusLambda": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProdEpilotKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ProdSchufaCert": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SchufaApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "TestEpilotKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TestSchufaCert": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}