export const SCHUFA_TEST_DATA = [
	{
		title: "",
		lastName: "MACH",
		firstName: "ERNST",
		gender: "MALE",
		dateOfBirth: "4/3/65",
		placeOfBirth: "",
		PLZ: "60487",
		Ort: "FRANKFURT",
		Straße: "JULIUSSTR. 39",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "FICHTE",
		firstName: "JOHANNES",
		gender: "MALE",
		dateOfBirth: "7/8/78",
		placeOfBirth: "",
		PLZ: "60323",
		Ort: "FRANKFURT",
		Straße: "LIEBIGSTR. 27",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "SENECA",
		firstName: "ZENON",
		gender: "MALE",
		dateOfBirth: "4/9/68",
		placeOfBirth: "",
		PLZ: "60385",
		Ort: "FRANKFURT",
		Straße: "ARNSBURGER STR. 5",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "ZARATHUSTRA",
		firstName: "ALSO SPRACH",
		gender: "WOMAN",
		dateOfBirth: "2/15/62",
		placeOfBirth: "",
		PLZ: "63069",
		Ort: "OFFENBACH",
		Straße: "DIELMANNSTR. 25",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "DANTE",
		firstName: "ALLIGHIRI",
		gender: "MALE",
		dateOfBirth: "1/16/62",
		placeOfBirth: "",
		PLZ: "63067",
		Ort: "OFFENBACH",
		Straße: "RATHAUSSTR. 19",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "BAUMWIPFELKRÄHENFINGERLINGSNESTBEFESTIGUNGSANKER",
		firstName: "KARL GUSTAV SIEGFRIED ERWIN WERNER FRIEDERICH ALFONS",
		gender: "MALE",
		dateOfBirth: "2/17/60",
		placeOfBirth: "",
		PLZ: "67071",
		Ort: "LUDWIGSHAFEN",
		Straße: "ROSENWÖRTHSTRAßE 35",
		Land: "Deutschland",
	},
	{
		title: "Prof.",
		lastName: "DERVERRÜCKTEPROFFESSORDERALLESWEIßUNDKEINEMETWASERZÄHLT",
		firstName: "GASTON ANDRÉ Jógvan Jákup Bølgen Rãñõfin BJÖRNES",
		gender: "MALE",
		dateOfBirth: "8/24/65",
		placeOfBirth: "",
		PLZ: "65232",
		Ort: "TAUNUSSTEIN",
		Straße: "WIESBADENERSTRAßE 100",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "Godt brød",
		firstName: "Eiganes",
		gender: "MALE",
		dateOfBirth: "4/12/89",
		placeOfBirth: "",
		PLZ: "4000",
		Ort: "Stavanger",
		Straße: "Eiganesveien 9",
		Land: "Norwegen",
	},
	{
		title: "",
		lastName: "BLOCH",
		firstName: "ERNST",
		gender: "MALE",
		dateOfBirth: "7/23/77",
		placeOfBirth: "",
		PLZ: "63075",
		Ort: "OFFENBACH",
		Straße: "LIMBURGER WEG 5",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "APOLLONIA",
		firstName: "DIOGENES",
		gender: "MALE",
		dateOfBirth: "12/10/80",
		placeOfBirth: "",
		PLZ: "60435",
		Ort: "FRANKFURT",
		Straße: "HUEGELSTR. 2",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "NATURICA",
		firstName: "DANA",
		gender: "WOMAN",
		dateOfBirth: "6/12/74",
		placeOfBirth: "",
		PLZ: "61348",
		Ort: "BAD HOMBURG",
		Straße: "CASTILLOSTR. 11",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "TECHNICA",
		firstName: "LAURA",
		gender: "WOMAN",
		dateOfBirth: "7/2/61",
		placeOfBirth: "",
		PLZ: "60435",
		Ort: "FRANKFURT",
		Straße: "ENGELTHALER STR. 16",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "LOGOS",
		firstName: "DANIEL",
		gender: "MALE",
		dateOfBirth: "6/18/74",
		placeOfBirth: "",
		PLZ: "60388",
		Ort: "FRANKFURT",
		Straße: "GEWINNERSTR. 34",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "LESSING",
		firstName: "EPHRAIM",
		gender: "MALE",
		dateOfBirth: "9/3/51",
		placeOfBirth: "",
		PLZ: "65929",
		Ort: "FRANKFURT",
		Straße: "ANTONITERSTR. 29",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "HEIDEGGER",
		firstName: "MARTIN",
		gender: "MALE",
		dateOfBirth: "7/28/53",
		placeOfBirth: "",
		PLZ: "64390",
		Ort: "ERZHAUSEN",
		Straße: "INDUSTRIESTR. 10",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "SVOERENSEN",
		firstName: "SVEN",
		gender: "MALE",
		dateOfBirth: "9/16/72",
		placeOfBirth: "",
		PLZ: "65195",
		Ort: "WIESBADEN",
		Straße: "SCHARNHORSTSTR. 7",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "POPPER",
		firstName: "KARL",
		gender: "MALE",
		dateOfBirth: "7/16/72",
		placeOfBirth: "",
		PLZ: "60311",
		Ort: "FRANKFURT",
		Straße: "BRAUBACHSTR. 39",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "GREBENSTEINER",
		firstName: "TINA",
		gender: "WOMAN",
		dateOfBirth: "5/18/78",
		placeOfBirth: "",
		PLZ: "60311",
		Ort: "FRANKFURT",
		Straße: "NEUE KRAEME 32",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "DORNBUSCH",
		firstName: "JONAS",
		gender: "MALE",
		dateOfBirth: "11/8/67",
		placeOfBirth: "",
		PLZ: "60529",
		Ort: "FRANKFURT",
		Straße: "MAURITIUSSTR. 13",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "GRASSMANN",
		firstName: "HEIKO",
		gender: "MALE",
		dateOfBirth: "7/12/85",
		placeOfBirth: "",
		PLZ: "60325",
		Ort: "FRANKFURT",
		Straße: "SCHUMANNSTR. 15",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "PIRASTRO",
		firstName: "VICTOR",
		gender: "MALE",
		dateOfBirth: "1/20/71",
		placeOfBirth: "",
		PLZ: "63065",
		Ort: "OFFENBACH",
		Straße: "HOSPITALSTR. 8",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "GUCKELMANN",
		firstName: "TOM",
		gender: "MALE",
		dateOfBirth: "6/27/71",
		placeOfBirth: "",
		PLZ: "60389",
		Ort: "FRANKFURT",
		Straße: "ROTHSCHILDALLEE 3",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "SANDNERS",
		firstName: "MIRIAM",
		gender: "WOMAN",
		dateOfBirth: "8/23/74",
		placeOfBirth: "",
		PLZ: "60311",
		Ort: "FRANKFURT",
		Straße: "BERLINER STR. 20",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "MINCKWITZ",
		firstName: "VIOLA",
		gender: "WOMAN",
		dateOfBirth: "6/12/71",
		placeOfBirth: "",
		PLZ: "60311",
		Ort: "FRANKFURT",
		Straße: "BERTHMANNSTR. 50",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "FRUEHAUF",
		firstName: "THOMAS",
		gender: "MALE",
		dateOfBirth: "9/6/73",
		placeOfBirth: "",
		PLZ: "60316",
		Ort: "FRANKFURT",
		Straße: "SANDWEG 9",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "SPAETDRAN",
		firstName: "JOSEPH",
		gender: "MALE",
		dateOfBirth: "8/25/71",
		placeOfBirth: "",
		PLZ: "60313",
		Ort: "FRANKFURT",
		Straße: "KLINGERSTR. 24",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "NIHUC",
		firstName: "MARIA",
		gender: "WOMAN",
		dateOfBirth: "11/22/73",
		placeOfBirth: "",
		PLZ: "60313",
		Ort: "FRANKFURT",
		Straße: "TAUBENSTR. 4",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "GRONEN",
		firstName: "TILL",
		gender: "MALE",
		dateOfBirth: "6/23/71",
		placeOfBirth: "",
		PLZ: "60487",
		Ort: "FRANKFURT",
		Straße: "AM LEONHARDSBRUNN 2",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "ARNOULI",
		firstName: "PAUL",
		gender: "MALE",
		dateOfBirth: "3/22/76",
		placeOfBirth: "",
		PLZ: "60325",
		Ort: "FRANKFURT",
		Straße: "RHEINSTR. 13",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "REST",
		firstName: "VEIT",
		gender: "MALE",
		dateOfBirth: "7/19/71",
		placeOfBirth: "",
		PLZ: "60318",
		Ort: "FRANKFURT",
		Straße: "HUMBOLDTSTR. 12",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "HASSLER",
		firstName: "TATJANA",
		gender: "WOMAN",
		dateOfBirth: "8/22/68",
		placeOfBirth: "",
		PLZ: "63073",
		Ort: "OFFENBACH",
		Straße: "GRAZER STR. 24",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "PRINZIPIELL",
		firstName: "PRINZIP",
		gender: "MALE",
		dateOfBirth: "2/28/65",
		placeOfBirth: "",
		PLZ: "63065",
		Ort: "OFFENBACH",
		Straße: "GELEITSTR. 13",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "ZEISERG",
		firstName: "BARBARA",
		gender: "WOMAN",
		dateOfBirth: "7/15/71",
		placeOfBirth: "",
		PLZ: "60313",
		Ort: "FRANKFURT",
		Straße: "STEPHANSTR. 15",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "MARGINAL",
		firstName: "MIA",
		gender: "WOMAN",
		dateOfBirth: "5/18/78",
		placeOfBirth: "",
		PLZ: "60329",
		Ort: "FRANKFURT",
		Straße: "NIDDASTR. 74",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "HUENLEIN",
		firstName: "YASMIN",
		gender: "WOMAN",
		dateOfBirth: "2/13/73",
		placeOfBirth: "",
		PLZ: "60323",
		Ort: "FRANKFURT",
		Straße: "ROSSERTSTR. 9",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "REINWALD",
		firstName: "JOHANNA",
		gender: "WOMAN",
		dateOfBirth: "2/11/74",
		placeOfBirth: "",
		PLZ: "60431",
		Ort: "FRANKFURT",
		Straße: "AM WIESENRAIN 17",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "LAUBINGER",
		firstName: "JANINA",
		gender: "WOMAN",
		dateOfBirth: "11/22/82",
		placeOfBirth: "",
		PLZ: "60322",
		Ort: "FRANKFURT",
		Straße: "ANNASTR. 7",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "SANDFORTH",
		firstName: "ROBERT",
		gender: "MALE",
		dateOfBirth: "4/15/82",
		placeOfBirth: "",
		PLZ: "60313",
		Ort: "FRANKFURT",
		Straße: "STEINWEG 8",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "STURMFELS",
		firstName: "KLAUS",
		gender: "MALE",
		dateOfBirth: "6/13/70",
		placeOfBirth: "",
		PLZ: "60594",
		Ort: "FRANKFURT",
		Straße: "GARTENSTR. 8",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "LEDERER",
		firstName: "MARINA",
		gender: "WOMAN",
		dateOfBirth: "12/15/71",
		placeOfBirth: "",
		PLZ: "60596",
		Ort: "FRANKFURT",
		Straße: "STRESEMANNALLEE 31",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "KNIPFER",
		firstName: "ANJA",
		gender: "WOMAN",
		dateOfBirth: "8/11/67",
		placeOfBirth: "",
		PLZ: "60318",
		Ort: "FRANKFURT",
		Straße: "OEDER WEG 34",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "DOEBERT",
		firstName: "CHARLOTTE",
		gender: "WOMAN",
		dateOfBirth: "5/28/65",
		placeOfBirth: "",
		PLZ: "60311",
		Ort: "FRANKFURT",
		Straße: "ROSENMARKT 10",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "HEGENLOH",
		firstName: "DOROTHEA",
		gender: "WOMAN",
		dateOfBirth: "1/30/69",
		placeOfBirth: "",
		PLZ: "60329",
		Ort: "FRANKFURT",
		Straße: "KAISERSTR. 79",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "KIRSCHHOCK",
		firstName: "PAULINE",
		gender: "WOMAN",
		dateOfBirth: "5/22/62",
		placeOfBirth: "",
		PLZ: "60488",
		Ort: "FRANKFURT",
		Straße: "HEERSTR. 57",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "PROSOLINGER",
		firstName: "THOMAS",
		gender: "MALE",
		dateOfBirth: "3/29/82",
		placeOfBirth: "",
		PLZ: "65719",
		Ort: "WALLAU",
		Straße: "TAUNUSSTR. 1",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "AUTODIDAKT",
		firstName: "JENS",
		gender: "MALE",
		dateOfBirth: "3/7/61",
		placeOfBirth: "",
		PLZ: "60386",
		Ort: "FRANKFURT",
		Straße: "AN DER MAINKUR 8",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "WEHRHEIM",
		firstName: "NADJA",
		gender: "WOMAN",
		dateOfBirth: "10/25/63",
		placeOfBirth: "",
		PLZ: "60327",
		Ort: "FRANKFURT",
		Straße: "CAMBERGER STR. 21",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "ERONO",
		firstName: "JULIA",
		gender: "WOMAN",
		dateOfBirth: "6/25/70",
		placeOfBirth: "",
		PLZ: "65195",
		Ort: "WIESBADEN",
		Straße: "SCHARNHORSTSTR. 6",
		Land: "Deutschland",
	},
	{
		title: "",
		lastName: "UTKENSTEIN",
		firstName: "MARKUS",
		gender: "MALE",
		dateOfBirth: "9/10/69",
		placeOfBirth: "",
		PLZ: "65201",
		Ort: "WIESBADEN",
		Straße: "HAGENAUER STR. 4",
		Land: "Deutschland",
	},
];

export const SCHUFA_MOCK_DATA = [
	{
		firstName: "Anna",
		lastName: "Beispiel",
		dateOfBirth: "1990-05-12",
		placeOfBirth: "Partytown",
		details: {
			value: 200,
			riskRate: 90.42,
			range: "K",
			text: "EVU-CHANCENSCORE K",
			infoText: [],
		},
		addresses: {
			currentAddress: {
				streetWithNumber: "Beispielweg 12",
				postalCode: "54321",
				city: "Beispielstadt",
				country: "Deutschland",
			},
			previousAddress: undefined,
		},
	},
	{
		firstName: "Lukas",
		lastName: "Mustermann",
		dateOfBirth: "1985-11-03",
		placeOfBirth: "Musterstadt",
		details: {
			value: 430,
			riskRate: 45.15,
			range: "G",
			text: "EVU-CHANCENSCORE G",
			infoText: [],
		},
		addresses: {
			currentAddress: {
				streetWithNumber: "Hauptstraße 77",
				postalCode: "10115",
				city: "Berlin",
				country: "Deutschland",
			},
			previousAddress: undefined,
		},
	},
	{
		firstName: "Svenja",
		lastName: "Testfrau",
		dateOfBirth: "1993-08-22",
		placeOfBirth: "Testdorf",
		details: {
			value: 615,
			riskRate: 25.4,
			range: "D",
			text: "EVU-CHANCENSCORE D",
			infoText: [],
		},
		addresses: {
			currentAddress: {
				streetWithNumber: "Teststraße 99",
				postalCode: "70173",
				city: "Stuttgart",
				country: "Deutschland",
			},
			previousAddress: undefined,
		},
	},
	{
		firstName: "Markus",
		lastName: "Schulz",
		dateOfBirth: "1979-02-17",
		placeOfBirth: "Altstadt",
		details: {
			value: 950,
			riskRate: 6.21,
			range: "A",
			text: "EVU-CHANCENSCORE A",
			infoText: [],
		},
		addresses: {
			currentAddress: {
				streetWithNumber: "Altweg 3",
				postalCode: "80331",
				city: "München",
				country: "Deutschland",
			},
			previousAddress: undefined,
		},
	},
];
